### ISSUE TITLE
Cannot configure cluster: DescribeJobFlows API is deprecated

### ISSUE THREAD

**Issue by mamigot** [edx/edx-analytics-configuration#17]
*I'm using ansible==1.4.4 and boto==2.38.0 as [requirements.txt states](https://github.com/edx/edx-analytics-configuration/blob/49df3b5ac39953adf4952c4e95dd9ec61534cbf2/requirements.txt). On Ubuntu 14.04, I'm running ansible 1.9*

Getting the following error while trying to [provision the cluster](https://github.com/edx/edx-analytics-configuration/blob/master/batch/provision.yml#L40):

```
TASK: [provision EMR cluster] ************************************************* 
failed: [localhost] => {"failed": true}
msg: Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-1441641147.08-229721865388324/emr", line 239, in main
    cluster = ElasticMapreduceCluster(name, region)
  File "/home/ubuntu/.ansible/tmp/ansible-1441641147.08-229721865388324/emr", line 42, in __init__
    self.jobflow = self.find_named_jobflow()
  File "/home/ubuntu/.ansible/tmp/ansible-1441641147.08-229721865388324/emr", line 45, in find_named_jobflow
    for cur_flow in self._emr.describe_jobflows(states=ALIVE_STATES):
  File "/usr/local/lib/python2.7/dist-packages/boto/emr/connection.py", line 137, in describe_jobflows
    return self.get_list('DescribeJobFlows', params, [('member', JobFlow)])
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
EmrResponseError: EmrResponseError: 400 Bad Request
<ErrorResponse xmlns="http://elasticmapreduce.amazonaws.com/doc/2009-03-31">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>DescribeJobFlows API is deprecated. Please refer to http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html for further information.</Message>
  </Error>
  <RequestId>70b67424-5578-11e5-8255-e1e4f588bc99</RequestId>
</ErrorResponse>



FATAL: all hosts have already failed -- aborting
```
It does seem as though [AWS has deprecated it](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_DescribeJobFlows.html), and is suggesting to use newer APIs to describe launch the EMR cluster.

Thank you!

**Comment by mamigot** [comment]
#15 seems to fix this

**Comment by brianhw** [comment]
We have just received notification that the API is being discontinued on December 14, so we'll get #15 merged before then!  But it's nice to know that it worked for someone other than just me.

**Comment by brianhw** [comment]
#15 is merged now, so this should be fixed.
